services:
  - type: web
    name: redza-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: redza_portfolio
      - key: CORS_ORIGINS
        sync: false
